# -*- coding:utf-8 -*-
from douban_client import DoubanClient
from xsettings import XCFG

API_KEY = XCFG.WECHAT_API_KEY
API_SECRET = XCFG.WECHAT_API_SECRET
REDIRECT_URI = XCFG.WECHAT_REDIRECT_URI
SCOPE = XCFG.WECHAT_SCOPE

client_wechat = DoubanClient(API_KEY, API_SECRET, REDIRECT_URI, SCOPE)

LOGIN_API_KEY = XCFG.LOGIN_API_KEY
LOGIN_API_SECRET = XCFG.LOGIN_API_SECRET
LOGIN_REDIRECT_URI = XCFG.LOGIN_REDIRECT_URI
LOGIN_SCOPE = XCFG.LOGIN_SCOPE


client_login = DoubanClient(LOGIN_API_KEY, LOGIN_API_SECRET, LOGIN_REDIRECT_URI, LOGIN_SCOPE)